[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "verify-diff-bin"
version = "0.1.0"
description = "A Rust-based terminal diff viewer for pytest-verify"
license = {text = "Apache-2.0"}
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.8"

[tool.maturin]
# 🟢 This is the key line: tell maturin to package the binary
bindings = "bin"
strip = true
